import type { Metadata } from "next";
import { Phudu, Roboto } from "next/font/google";
import "./globals.css";
import HeroPage from "./Hero/Page.tsx";
import Footer from "@/components/Footer";

const phudu = Phudu({
  variable: "--font-phudu",
  subsets: ["latin"],
  weight: ['300' , '400', '500' , '600' , '700' , '800' , '900'],
  display : 'swap'
});

const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${phudu.variable} ${roboto.variable} antialiased `}
      >
        <HeroPage/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
